# Generated by Django 5.2.11 on 2026-02-26 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('midi_dir', models.CharField(max_length=512)),
                ('num_songs', models.IntegerField(default=0)),
                ('vocabulary_json', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('tempo', models.FloatField()),
                ('duration', models.FloatField()),
                ('instruments_json', models.JSONField(default=list)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='corpus.corpusscan')),
            ],
        ),
    ]
