# Generated by Django 5.2.11 on 2026-02-26 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('stopped', 'Stopped')], default='pending', max_length=20)),
                ('config_json', models.JSONField(default=dict)),
                ('current_phase', models.IntegerField(default=1)),
                ('total_steps', models.IntegerField(default=0)),
                ('latest_error', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('avg_error', models.FloatField()),
                ('phase', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='training.trainingrun')),
            ],
            options={
                'ordering': ['step'],
            },
        ),
    ]
